version: "3.3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./conf.d/proxy-wide.conf:/etc/nginx/conf.d/proxy-wide.conf
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./conf.d/proxy-wide.conf:/etc/nginx/conf.d/proxy-wide.conf
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
  whoami:
    image: jwilder/whoami
    container_name: whoami
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: whoami.local
